apiVersion: v1
kind: Service
metadata:
  name: story-service # name of the service
spec:
  selector:
    app: story # label to select the pods to route traffic to
  ports:
    - protocol: TCP # protocol to use for the service
      port: 80 # port to expose the service on(the outside world port)
      targetPort: 3000 # port to forward traffic to on the pod (the internal container port)
      # You can add multiple ports to the service if needed:
#   - protocol: TCP 
#     port: 443 
#     targetPort: 8443 
  type: LoadBalancer # type of service to create (LoadBalancer, NodePort, ClusterIP)